language: rust

cache:
  cargo: true
  directories:
    - /home/travis/BYOND/

jobs:
  include:
    - os: windows
      env: BUILD_TARGET=i686-pc-windows-msvc
    - os: linux
      env: BUILD_TARGET=i686-unknown-linux-gnu
      before_script:
        - env BYOND_MAJOR=513 BYOND_MINOR=1521 ./scripts/install_byond.sh
        - export BYOND_BIN=/home/travis/BYOND/byond/bin
        - export PKG_CONFIG_ALLOW_CROSS=1
      after_script: cargo test --target $BUILD_TARGET --verbose --all --release --all-features

addons:
  apt:
    - g++-multilib
    - libssl-dev:i386

install:
  - rustup target add $BUILD_TARGET

script:
  - cargo build --target $BUILD_TARGET --verbose --all --release --all-features || travis_terminate 1; fi
